version: '3.8'

services:
  nginx:
    container_name: mynginx
    restart: always
    image: nginx:1.16.1
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx    
