server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      discovery:
        service-id: config-server
      profile: dev
      label: master

#      routes:
#        - id: custom_add_request_header_route
#          uri: lb://gateway
#          order: 0
#          predicates:
#            - Path=/gateway/**
#          filters:
#            - CustomAddRequestHeader=customHeaderName,customHeaderValue


logging:
  level:
    org.springframework.cloud.gateway: debug