server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server2:8002/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/config?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: config-server
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where position(? in APPLICATION) and PROFILE=? and LABEL=?

